---

- name: Slurm Controller Create
  become: true
  hosts: all
  vars:
#    slurm_roles: ['controller', 'exec', 'dbd']
    slurm_roles: ['controller']
  roles:
    - rhel_common
    - galaxyproject.slurm

