---

- name: Slurm Controller Create
  become: true
  hosts: slurmexechosts
  vars:
#    slurm_roles: ['controller', 'exec', 'dbd']
    slurm_roles: ['exec']
  roles:
    - rhel_common
    - galaxyproject.slurm

